version: '3'

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nextbasket_users
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app_network
  users:
    build:
      context: ./users
    ports:
      - "8000:80"
    depends_on:
      - mysql
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=nextbasket_users
      - DB_USERNAME=root
      - DB_PASSWORD=root

  notifications:
    build:
      context: ./notifications
    depends_on:
      - mysql
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=nextbasket
      - DB_USERNAME=root
      - DB_PASSWORD=root

  message-broker:
    image: "rabbitmq:management"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - app_network

networks:
  app_network:

volumes:
  mysql_data:
